### ISSUE TITLE
RuntimeError: clWaitForEvents failed: OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by libra146** [whiteblackitty/SQLCipher-Password-Cracker-OpenCL#2]
When I run `python Run.py 1`, it goes wrong.
This is my configuration and error message
```
Encrypted Database: EnMicroMsg.db
Reading encrypted data...
Init OpenCL...

Using Platform 1:
--------------------------------------------------------------------------
 Device - Name: GeForce GT 755M
 Device - Type: ALL | GPU
 Device - Compute Units: 2
 Device - Max Work Group Size: 1024

Compiling OpenCL Code...

Starting OpenCL Kernel...

Traceback (most recent call last):
  File ".\Run.py", line 202, in <module>
    main(sys.argv)
  File ".\Run.py", line 175, in main
    result=opencl_ctx.run(Innercycle*i,Innercycle,False) # core function, it's suggested that the Innercycle should be integer number of workgroupsize
  File "D:\SQLCipher-Password-Cracker-OpenCL-master\Lib\opencl.py", line 133, in run
    finish_event.wait()
pyopencl._cl.RuntimeError: clWaitForEvents failed: OUT_OF_RESOURCES



PBKDF2-noHMAC-SHA1--AES-256-CBC encrypted SQLite database cracking v2018

============================================================
OpenCL Platforms and Devices
============================================================
Platform 0 - Name: Intel(R) OpenCL
Platform 0 - Vendor: Intel(R) Corporation
Platform 0 - Version: OpenCL 1.2
Platform 0 - Profile: FULL_PROFILE
 --------------------------------------------------------
 Device - Name: Intel(R) HD Graphics 4600
 Device - Type: ALL | GPU
 Device - Max Clock Speed: 1150 Mhz
 Device - Compute Units: 20
 Device - Local Memory: 64 KB
 Device - Constant Memory: 64 KB
 Device - Global Memory: 2 GB
 Device - Max Buffer/Image Size: 407 MB
 Device - Max Work Group Size: 512


 --------------------------------------------------------
 Device - Name: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
 Device - Type: ALL | CPU
 Device - Max Clock Speed: 2500 Mhz
 Device - Compute Units: 4
 Device - Local Memory: 32 KB
 Device - Constant Memory: 128 KB
 Device - Global Memory: 8 GB
 Device - Max Buffer/Image Size: 2026 MB
 Device - Max Work Group Size: 8192


============================================================
Platform 1 - Name: NVIDIA CUDA
Platform 1 - Vendor: NVIDIA Corporation
Platform 1 - Version: OpenCL 1.2 CUDA 8.0.0
Platform 1 - Profile: FULL_PROFILE
 --------------------------------------------------------
 Device - Name: GeForce GT 755M
 Device - Type: ALL | GPU
 Device - Max Clock Speed: 1019 Mhz
 Device - Compute Units: 2
 Device - Local Memory: 48 KB
 Device - Constant Memory: 64 KB
 Device - Global Memory: 2 GB
 Device - Max Buffer/Image Size: 512 MB
 Device - Max Work Group Size: 1024


============================================================
Platform 0 - Name Intel(R) OpenCL, Vendor Intel(R) Corporation
Platform 1 - Name NVIDIA CUDA, Vendor NVIDIA Corporation
============================================================

Please run as: python opencl_test.py [platform number]
```

**Comment by libra146** [comment]
My system environment is win10, 64 bit, CUDA version is
![image](https://user-images.githubusercontent.com/17448639/83498230-31a09280-a4ee-11ea-99b2-cd136c69acc3.png)
I have installed Python3.7 64 bit

**Comment by whiteblackitty** [comment]
Please try setting OUTER_PASS_LENGTH = 3 or more (but must be less than TOTAL_PASS_LENGTH).

**Comment by libra146** [comment]
> Please try setting OUTER_PASS_LENGTH = 3 or more (but must be less than TOTAL_PASS_LENGTH).

It worked, thanks!!
